# Generated by Django 4.2.2 on 2023-11-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depots', '0002_depot_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depot',
            options={'permissions': [('view_depot_portal', 'Can view Depot Portal')]},
        ),
    ]
