# Generated by Django 4.2.2 on 2023-11-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_bulkctm_device_alter_bulkctm_lot_number_and_more'),
        ('depots', '0003_alter_depot_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField()),
                ('bulk_ctm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_ctm_inventory', to='supplier.bulkctm')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depots.depot')),
                ('individual_ctm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_ctm_inventory', to='supplier.individualctm')),
            ],
        ),
    ]
