# Generated by Django 4.2.2 on 2023-11-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_remove_bulkctm_depot_remove_individualctm_depot'),
        ('depots', '0004_depotinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotinventory',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.suppliershipment'),
        ),
    ]
