# Generated by Django 4.2.2 on 2023-11-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctm_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalsite',
            options={'permissions': [('view_ctm_tracking_portal', 'Can view CTM Tracking Portal')]},
        ),
    ]
