# Generated by Django 4.2.2 on 2023-06-25 19:12

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name='Admin')
    Group.objects.get_or_create(name='Study Coordinator')
    Group.objects.get_or_create(name='Inventory Manager')
    Group.objects.get_or_create(name='Medical Monitor')
    Group.objects.get_or_create(name='Pharmacist')
    Group.objects.get_or_create(name='Clinical Trial Manager')
    Group.objects.get_or_create(name='Depot User')
    Group.objects.get_or_create(name='Supplier')


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(create_groups),
    ]
