# Generated by Django 4.2.2 on 2023-07-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctm_type', models.CharField(choices=[('Bulk', 'Bulk'), ('Individual', 'Individual')], max_length=10)),
                ('device', models.CharField(max_length=200)),
                ('lot_number', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('expiration_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualCTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctm_type', models.CharField(choices=[('Bulk', 'Bulk'), ('Individual', 'Individual')], max_length=10)),
                ('device', models.CharField(max_length=200)),
                ('lot_number', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('expiration_date', models.DateField()),
                ('kit_serial_number', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
