# Generated by Django 4.2.2 on 2023-11-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depots', '0004_depotinventory'),
        ('supplier', '0003_alter_bulkctm_device_alter_bulkctm_lot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkctm',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_ctms', to='depots.depot'),
        ),
        migrations.AddField(
            model_name='individualctm',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_ctms', to='depots.depot'),
        ),
        migrations.AlterField(
            model_name='bulkctm',
            name='device',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bulkctm',
            name='lot_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bulkctm',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='individualctm',
            name='device',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='individualctm',
            name='lot_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='individualctm',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
