# Generated by Django 4.2.2 on 2023-11-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_bulkctm_depot_individualctm_depot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkctm',
            old_name='device',
            new_name='ctm_name',
        ),
        migrations.RenameField(
            model_name='individualctm',
            old_name='device',
            new_name='ctm_name',
        ),
    ]
