# Generated by Django 4.2.2 on 2023-11-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_rename_device_bulkctm_ctm_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkctm',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='individualctm',
            name='depot',
        ),
    ]
