# Generated by Django 4.2.2 on 2023-11-18 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depots', '0004_depotinventory'),
        ('supplier', '0006_remove_bulkctm_depot_remove_individualctm_depot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Shipped', 'Shipped')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('view_supplier_shipment', 'Can view supplier shipments')],
            },
        ),
        migrations.DeleteModel(
            name='SupplierPortal',
        ),
        # migrations.RemoveField(
        #     model_name='bulkctm',
        #     name='depot',
        # ),
        # migrations.RemoveField(
        #     model_name='individualctm',
        #     name='depot',
        # ),
        migrations.AddField(
            model_name='suppliershipment',
            name='bulk_ctm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.bulkctm'),
        ),
        migrations.AddField(
            model_name='suppliershipment',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depots.depot'),
        ),
        migrations.AddField(
            model_name='suppliershipment',
            name='individual_ctm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.individualctm'),
        ),
        migrations.AddField(
            model_name='suppliershipment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
