# Generated by Django 4.2.2 on 2023-11-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_suppliershipment_delete_supplierportal_and_more'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='bulkctm',
    #         name='depot',
    #     ),
    #     migrations.RemoveField(
    #         model_name='individualctm',
    #         name='depot',
    #     ),
    # ]
