# Generated by Django 4.2.2 on 2023-11-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_suppliershipment_bulk_ctm_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctm_type', models.CharField(choices=[('Bulk', 'Bulk'), ('Individual', 'Individual')], max_length=10)),
                ('ctm_name', models.CharField(max_length=200)),
                ('lot_number', models.CharField(max_length=200)),
                ('expiration_date', models.DateField()),
                ('kit_serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bulk_batch_id', models.IntegerField(blank=True, null=True)),
                ('bulk_ctm_identifier', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
