# Generated by Django 4.2.2 on 2023-12-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_ctm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CTM',
            new_name='CTMInventory',
        ),
    ]
