# Generated by Django 4.2.2 on 2023-12-03 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0011_rename_ctm_ctminventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryCTMInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ctm_type', models.CharField(choices=[('Bulk', 'Bulk'), ('Individual', 'Individual')], max_length=10)),
                ('ctm_name', models.CharField(max_length=200)),
                ('lot_number', models.CharField(max_length=200)),
                ('expiration_date', models.DateField()),
                ('kit_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Temporary CTM Inventory',
                'verbose_name_plural': 'Temporary CTM Inventories',
            },
        ),
    ]
